import os
from datetime import datetime


class ClientReportBuilder:

    def __init__(self, client_name, system_results):
        self.client_name = client_name
        self.data = system_results

    # ---------------------------------------

    def format_list(self, items):

        if not items:
            return "None"

        return "\n".join([f"- {item}" for item in items])

    # ---------------------------------------

    def build_report(self):

        report = f"""
# {self.client_name} — Growth Intelligence Report

Generated: {datetime.now().strftime("%Y-%m-%d")}

---

# Executive Summary

{self.data["recommendation"]}

---

# Business Diagnosis

Rating: {self.data["rating"]}
Reviews: {self.data["reviews"]}
Social Status: {self.data["social_status"]}
Core Problem: {self.data["core_problem"]}

---

# Revenue Model

Average Order Value: {self.data["aov"]}
Monthly Customers: {self.data["monthly_customers"]}
Customer Frequency: {self.data["frequency"]}

---

# Strategic Growth Plan

Primary Strategy:
{self.data["primary_lever"]}

Campaign Framework:
{self.data["campaign_type"]}

Content Strategy:
{self.data["offer_strategy"]}

Growth Focus:
{self.data["sales_angle"]}

---

# Creative Execution Ideas

Hooks:
{self.format_list(self.data["hooks"])}

Reel Ideas:
{self.format_list(self.data["reel_ideas"])}

Poster Concepts:
{self.format_list(self.data["poster_concepts"])}

---

# Conversion Intelligence

Conversion Probability: {self.data["conversion_probability"]}
Performance Tier: {self.data["performance_tier"]}

---

# Marketing Funnel Projection

Reach → Engagement → Click → Conversion

{self.data["reach"]} → {self.data["engagement"]} → {self.data["clicks"]} → {self.data["conversions"]}

---

# KPI Targets

Expected Revenue Increase: {self.data["annual_revenue_increase"]}

ROI Projection: {self.data["roi"]}

Payback Period: {self.data["payback_period"]}

---

# Risk Analysis

Risk Score: {self.data["risk_score"]}

Warnings:
{self.format_list(self.data["risk_warnings"])}

---

# Suitability Analysis

Suitability Score: {self.data["suitability_score"]}

Warnings:
{self.format_list(self.data["suitability_warnings"])}

---

# 90 Day Action Plan

Month 1:
{self.data["month1"]}

Month 2:
{self.data["month2"]}

Month 3:
{self.data["month3"]}

---

Generated by AI Marketing Consultant System
"""

        return report

    # ---------------------------------------

    def save_report(self):

        report = self.build_report()

        os.makedirs("clients", exist_ok=True)

        file_path = f"clients/{self.client_name}_growth_report.md"

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(report)

        return file_path